'use client';
import {useEffect,useState,useRef} from 'react';
import {playAnswerSound} from '../lib/answer-sound';
import {ProgressSync} from '../lib/progress-sync';
import {Progress as ProgressBar} from '@/components/ui/progress';
import {BookOpen,Library,Layers,House,ChevronLeft,Check,Lock,Flame,RotateCcw,Leaf,Volume2,VolumeX} from 'lucide-react';
import {lessons,words,initial,intervals,type Progress} from '../lib/course';
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function Page(){
 const [p,P]=useState<Progress>(initial),[ready,Ready]=useState(false),[needsLogin,NeedsLogin]=useState(false),[saving,Saving]=useState(false),[sound,Sound]=useState(true),[error,E]=useState(''),[view,V]=useState('home'),[flip,F]=useState(false),[feedback,FB]=useState(''),[queue,Q]=useState<number[]>([]),[sessionCount,SC]=useState(0);const sync=useRef<ProgressSync|null>(null);const lastAction=useRef(0);const swiped=useRef(false);const start=useRef<{x:number,y:number}|null>(null);
 async function load(){E('');try{const r=await fetch('/api/progress',{signal:AbortSignal.timeout(10000)});if(r.status===401){NeedsLogin(true);return;}const d=await r.json() as {data:Progress;revision:number;error:string};if(!r.ok)throw Error(d.error);sync.current?.dispose();sync.current=new ProgressSync(d.revision,fetch,(pending,message)=>{Saving(pending);E(message)});P(d.data);Ready(true);}catch(e){E((e as Error).name==='TimeoutError'?'Сервер долго отвечает. Нажмите «Повторить».':(e as Error).message);}}
 useEffect(()=>{try{Sound(localStorage.getItem('arabikos-sound')!=='off')}catch{}},[]);
 useEffect(()=>{load();const online=()=>sync.current?.retry();const leaving=(e:BeforeUnloadEvent)=>{if(sync.current?.dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('online',online);window.addEventListener('beforeunload',leaving);return()=>{sync.current?.dispose();window.removeEventListener('online',online);window.removeEventListener('beforeunload',leaving);}},[]);
 useEffect(()=>{const mc=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!mc)return;const c=new AbortController();try{Promise.resolve(mc.registerTool({name:'read_learning_progress',description:'Read completed lessons and learned words without changing progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');const r=await fetch('/api/progress');if(!r.ok)throw Error('Progress unavailable');const d=await r.json() as {data:Progress;revision:number;error:string};return {completedLessons:d.data.completed.length,learnedWords:d.data.completed.length*10};}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort();},[]);
 function save(n:Progress){P(n);sync.current?.enqueue(n);return true;}
 function acceptAction(){const now=performance.now();if(now-lastAction.current<160)return false;lastAction.current=now;return true;}
 const learned=words.filter(w=>p.completed.includes(w.lesson));const due=learned.filter(w=>(p.reviews[w.id]?.due??0)<=Date.now());const current=lessons[Math.min(p.lesson,9)];const allDone=p.completed.length===lessons.length;const step=p.step;const activeWord=current.words[step<10?step:Math.min(step-13,9)];
 function activity(n:Progress){const k=dayKey();return {...n,days:{...n.days,[k]:(n.days[k]??0)+1}};}
 function advance(){if(!acceptAction())return;if(step>=13&&sound)playAnswerSound(true);if(step===22){const completed=Array.from(new Set([...p.completed,current.id]));const reviews={...p.reviews};current.words.forEach(w=>{if(!reviews[w.id])reviews[w.id]={level:0,due:Date.now(),seen:0}});if(save(activity({...p,completed,reviews,lesson:Math.min(current.id+1,9),step:0})))V('complete');}else if(save({...p,step:step+1})){F(false);FB('');}}
 function go(v:string){V(v);F(false);FB('');}
 function review(ids=due.map(w=>w.id)){Q(ids);SC(0);F(false);V('review');}
 function grade(known:boolean){if(!queue.length||!acceptAction())return;if(sound)playAnswerSound(known);const id=queue[0],old=p.reviews[id]??{level:0,due:0,seen:0};const level=known?Math.min(old.level+1,intervals.length):Math.max(0,old.level-1);const delay=known?intervals[Math.max(0,level-1)]:60000;if(save(activity({...p,reviews:{...p.reviews,[id]:{level,due:Date.now()+delay,seen:old.seen+1}}}))){Q(known?queue.slice(1):[...queue.slice(1),id]);SC(sessionCount+1);F(false);}}
 let streak=0;{const d=new Date();if(!p.days[dayKey(d)])d.setDate(d.getDate()-1);while(p.days[dayKey(d)]){streak++;d.setDate(d.getDate()-1);}}
 const arabic=(ids:number[])=>ids.map(id=>words[id].ar).join(' ');
 return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();go('home')}}><span className="brandmark">ا</span><span>Арабикос<small>ЧИТАТЬ. ПОНИМАТЬ.</small></span></a><div className="side-label">ВАША КНИГА</div><nav>{([['home','Главная',House],['lessons','Уроки',BookOpen],['dictionary','Мой словарь',Library],['review','Повторение',Layers]] as const).map(([key,label,Icon])=><button key={String(key)} className={view===key?'nav active':'nav'} onClick={()=>key==='review'?review():go(String(key))}><Icon size={20}/><span>{String(label)}</span>{key==='review'&&due.length>0&&<b>{due.length}</b>}</button>)}</nav><div className="side-bottom"><Leaf size={24}/><p>Знание растёт<br/>с каждой страницей.</p><small>По 10 слов за один шаг</small></div><span className="edition">АРАБСКИЙ ДЛЯ ПОНИМАНИЯ КОРАНА</span></aside>
 <div className="workspace"><header><span>Личная книга знаний{ready&&<small className="sync-status" role="status">{saving?'Сохраняем…':'Сохранено'}</small>}</span><div><button className="sound-toggle" aria-label={sound?'Отключить звуки':'Включить звуки'} aria-pressed={sound} title={sound?'Звук включён':'Звук выключен'} onClick={()=>{const next=!sound;Sound(next);try{localStorage.setItem('arabikos-sound',next?'on':'off')}catch{}}}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><Flame size={17}/><span>{streak} {streak===1?'день':'дн.'} подряд</span><span className="avatar"><BookOpen size={16}/></span>{ready&&<a className="textbtn" href="/signout-with-chatgpt?return_to=%2F" target="_top">Выйти</a>}</div></header><main>
 {error&&<div className="error" role="alert">{error} {!ready?<button onClick={load}>Повторить</button>:<button onClick={()=>sync.current?.retry()}>Повторить сохранение</button>}</div>}
 {needsLogin?<section className="empty"><BookOpen size={42}/><div className="eyebrow">АРАБСКИЙ ДЛЯ ПОНИМАНИЯ КОРАНА</div><h1>Ваша личная книга знаний</h1><p>10 уроков по 10 слов, предложения из изученного и карточки для повторения. Войдите, чтобы сохранить свой прогресс и продолжать с любого устройства.</p><a className="primary" href="/signin-with-chatgpt?return_to=%2F" target="_top">Войти через ChatGPT</a></section>:!ready?<div className="empty"><BookOpen/><h2>{error?'Книга пока недоступна':'Открываем вашу книгу…'}</h2></div>:<>
 {view==='home'&&<><div className="pageheading"><div><div className="eyebrow">СТРАНИЦА ЗА СТРАНИЦЕЙ</div><h1>Ваш путь к пониманию</h1><p>Немного каждый день. Смысл — в каждом слове.</p></div><span className="chapter-number">01</span></div><section className="stats"><div><span>Слов в вашей книге</span><strong>{learned.length}<small> / 100</small></strong><ProgressBar className="line" value={learned.length} aria-label="Изучено слов"/></div><div><span>Уроков пройдено</span><strong>{p.completed.length}<small> / 10</small></strong><span className="muted">Каждый урок — 10 новых слов</span></div><div><span>Ждут повторения</span><strong>{due.length}<small> слов</small></strong><button className="textbtn" onClick={()=>review()}>Открыть карточки</button></div></section>
 <div className="home-grid"><section className="book-feature"><div className="book-top"><span className="eyebrow">{allDone?'ПЕРВАЯ ГЛАВА ЗАВЕРШЕНА':'ПРОДОЛЖИТЬ ИЗУЧЕНИЕ'}</span><span>Урок {current.id+1} из 10</span></div><div className="feature-content"><div><span className="badge">{allDone?'100 слов в словаре':step===0?'Новая страница':`Шаг ${step+1} из 23`}</span><h2>{allDone?'Знание остаётся с вами':current.title}</h2><p>{allDone?'Повторяйте знакомые слова, чтобы узнавать их увереннее.':current.subtitle}</p><button className="primary" onClick={()=>allDone?review():go('lesson')}><BookOpen size={18}/>{allDone?'Повторить слова':step?'Продолжить урок':'Открыть урок'}</button><small>10 слов · 3 предложения · проверка</small></div><div className="feature-ar" lang="ar" dir="rtl">{allDone?'عِلْمٌ':current.words[0].ar}<span>{allDone?'знание':current.words[0].ru}</span></div></div><div className="book-foot"><span>Только знакомые слова в предложениях</span><span>✦</span></div></section><section className="activity"><div className="section-title"><h3>Ритм занятий</h3><Flame size={19}/></div><strong>{streak}<small> дней подряд</small></strong><div className="week">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return <div key={i}><span>{d.toLocaleDateString('ru',{weekday:'short'})}</span><b className={p.days[dayKey(d)]?'filled':i===6?'today':''}>{p.days[dayKey(d)]?<Check size={16}/>:d.getDate()}</b></div>})}</div><p>{p.days[dayKey()]?'Сегодня вы уже сделали шаг вперёд.':'Один небольшой урок — хорошее начало дня.'}</p></section></div>
 <div className="section-title lesson-heading"><h2>Следующие страницы</h2><button className="textbtn" onClick={()=>go('lessons')}>Все уроки</button></div><div className="lesson-grid">{lessons.slice(Math.min(p.lesson,7),Math.min(p.lesson,7)+3).map(l=><LessonTile key={l.id} l={l} p={p} open={()=>go('lesson')}/>)}</div><div className="quiet-note"><span>✦</span><p>Сначала понимание, потом запоминание.<br/><small>Новые слова попадут в словарь после полного завершения урока.</small></p></div></>}
 {view==='lessons'&&<><div className="eyebrow">ОГЛАВЛЕНИЕ</div><h1>Десять первых глав</h1><p className="intro">От первых смыслов к простым предложениям. Проходите уроки по порядку.</p><div className="lesson-grid full">{lessons.map(l=><LessonTile key={l.id} l={l} p={p} open={()=>go('lesson')}/>)}</div><p className="source">Порядок учитывает частотность и возможность строить простые фразы. <a href="https://corpus.quran.com/lemmas.jsp" target="_blank" rel="noreferrer">Справочник: Quranic Arabic Corpus</a>. Учебные предложения не выдаются за цитаты из Корана.</p></>}
 {view==='lesson'&&<><button className="textbtn" onClick={()=>go('home')}><ChevronLeft size={17}/> К моей книге</button><div className="study-heading"><div><div className="eyebrow">УРОК {current.id+1} · {step<10?'СЛОВА':step<13?'ПРЕДЛОЖЕНИЯ':'ПРОВЕРКА'}</div><h1>{current.title}</h1></div><span>{step+1} / 23</span></div><ProgressBar className="line studyline" value={(step+1)/23*100} aria-label="Прогресс урока"/><section className="study-card" key={step}>{step<10?<><span className="eyebrow">СЛОВО {step+1} ИЗ 10</span><div className="arabic giant" lang="ar" dir="rtl">{activeWord.ar}</div><h2>{activeWord.ru}</h2><p>Прочитайте слово и запомните его смысл.</p><button className="primary" onClick={advance}>Дальше</button></>:step<13?<><span className="eyebrow">УЧЕБНОЕ ПРЕДЛОЖЕНИЕ {step-9} ИЗ 3</span><div className="arabic sentence" lang="ar" dir="rtl">{arabic(current.examples[step-10].ids)}</div><button className="textbtn center" onClick={()=>F(!flip)}>{flip?'Скрыть перевод':'Показать перевод'}</button>{flip&&<h2>{current.examples[step-10].ru}</h2>}<p>Все слова — из этого и предыдущих уроков.</p><button className="primary" onClick={advance}>Прочитал, дальше</button></>:<><span className="eyebrow">ВЫБЕРИТЕ ПЕРЕВОД · {step-12} / 10</span><div className="arabic giant" lang="ar" dir="rtl">{activeWord.ar}</div><div className="answers">{[activeWord,...current.words.filter(w=>w.id!==activeWord.id).slice(0,3)].sort((a,b)=>(a.id*7+step)%11-(b.id*7+step)%11).map(w=><button key={w.id} onClick={()=>{if(w.id===activeWord.id)advance();else {if(sound)playAnswerSound(false);FB('Попробуйте ещё раз.')}}} className={feedback==='Верно!'&&w.id===activeWord.id?'correct':''}>{w.ru}</button>)}</div><p role="status">{feedback||'Вспомните значение слова.'}</p></>}</section></>}
 {view==='complete'&&<section className="empty completion"><Check size={45}/><div className="eyebrow">ЕЩЁ ОДНА СТРАНИЦА</div><h1>Урок пройден!</h1><p>10 новых слов теперь в вашем словаре.<br/>Первое повторение уже доступно.</p><button className="primary" onClick={()=>review()}>Закрепить слова</button><button className="textbtn center" onClick={()=>go('home')}>Вернуться на главную</button></section>}
 {view==='dictionary'&&<><div className="eyebrow">СОБРАНО ПО СЛОВУ</div><div className="section-title"><h1>Мой словарь <small>{learned.length}</small></h1>{learned.length>0&&<button className="primary" onClick={()=>review(learned.map(w=>w.id))}><Layers size={18}/>Карточки</button>}</div>{!learned.length?<div className="empty"><Library size={40}/><h2>Здесь начнётся ваша коллекция</h2><p>Пройдите первый урок полностью — и в словаре появятся 10 слов.</p><button className="primary" onClick={()=>go('lesson')}>Открыть первый урок</button></div>:<div className="dictionary">{learned.map(w=><div key={w.id}><span className="arabic" lang="ar" dir="rtl">{w.ar}</span><div><strong>{w.ru}</strong><small>Урок {w.lesson+1} · {p.reviews[w.id]?.seen?'Повторений: '+p.reviews[w.id].seen:'Ещё не повторяли'}</small></div></div>)}</div>}</>}
 {view==='review'&&<><div className="eyebrow">ПОВТОРЕНИЕ С ИНТЕРВАЛАМИ</div><div className="section-title"><h1>Вспомнить знакомое</h1><span>Осталось {queue.length}</span></div>{queue.length?<><button className={'flashcard '+(flip?'flipped':'')} onClick={()=>{if(swiped.current){swiped.current=false;return;}F(!flip)}} onPointerDown={e=>{swiped.current=false;e.currentTarget.setPointerCapture(e.pointerId);start.current={x:e.clientX,y:e.clientY}}} onPointerUp={e=>{if(start.current){const dx=e.clientX-start.current.x,dy=e.clientY-start.current.y;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)){e.preventDefault();swiped.current=true;grade(dx>0)}start.current=null}}}><span className="eyebrow">{flip?'ПРОВЕРЬТЕ СЕБЯ':'ВСПОМНИТЕ ПЕРЕВОД'}</span><span className="arabic giant" lang="ar" dir="rtl">{words[queue[0]].ar}</span>{flip?<strong>{words[queue[0]].ru}</strong>:<span className="muted">Нажмите на карточку, чтобы посмотреть перевод</span>}</button><div className="review-actions"><button onClick={()=>grade(false)}><RotateCcw size={18}/>Не помню</button><button className="primary" onClick={()=>grade(true)}><Check size={18}/>Помню</button></div><p className="swipe-note">Свайп влево — не помню, вправо — помню.<br/>Отвечайте сразу. Перевод открывается только по нажатию на карточку.</p><button className="textbtn center" onClick={()=>go('home')}>Закончить повторение</button></>:<div className="empty"><Check size={40}/><h2>{sessionCount?'Отличная работа!':'На сейчас всё'}</h2><p>{learned.length?'Карточек к повторению пока нет. Можно вернуться позже или повторить все слова.':'Сначала завершите первый урок — здесь появятся ваши слова.'}</p>{learned.length?<button className="primary" onClick={()=>review(learned.map(w=>w.id))}>Повторить все слова</button>:<button className="primary" onClick={()=>go('lesson')}>Начать урок</button>}</div>}</>}
 </>}
 <footer><span>АРАБИКОС</span><span>Путь начинается с одного слова</span><span>✦</span></footer></main></div></div>
}
function LessonTile({l,p,open}:{l:typeof lessons[number];p:Progress;open:()=>void}){const done=p.completed.includes(l.id),locked=l.id>p.lesson;return <button className={'lesson-tile '+(locked?'locked':'')+(done?' done':'')} disabled={locked||done} onClick={open}><div className="tile-top"><span>УРОК {String(l.id+1).padStart(2,'0')}</span>{done?<Check size={18}/>:locked?<Lock size={16}/>:<BookOpen size={18}/>}</div><h3>{l.title}</h3><p>{l.subtitle}</p><div className="tile-bottom"><span>10 слов</span><span>{done?'Пройден':locked?'Впереди':'Начать'}</span></div></button>}
