import {usePronunciation} from './lib/pronunciation';
import {dictionaryWords} from './lib/dictionary-order';
import {LessonsPage} from './Lessons';
import {Alphabet,AlphabetWelcome} from './Alphabet';
import {useEffect,useState,useRef} from 'react';
import {SettingsPage} from './Settings';
import {Motivation} from './Motivation';
import {repeatLabel} from './lib/review-time';
import {weakWords,clearDifficultWord} from './lib/spelling';
import {WordBuilder} from './WordBuilder';
import {PracticeHub,SentencePractice,VerbPractice} from './Practice';
import {scheduleReview} from './lib/repetition';
import {playAnswerSound} from './lib/answer-sound';
import {KEY,readProgress,writeProgress} from './lib/storage';
function ProgressBar({value,className,...props}:{value:number;className:string;'aria-label':string}){return <div className={className} role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={value} {...props}><i style={{width:value+'%'}}/></div>}
import {BookOpen,Library,Layers,House,ChevronLeft,Check,Lock,Flame,RotateCcw,Leaf,Settings,Volume2,VolumeX,Moon,Sun} from 'lucide-react';
import {lessons,words,initial,type Progress} from './lib/course';
const dayKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export default function Page(){
 const [p,P]=useState<Progress>(initial),[ready,Ready]=useState(false),[unsaved,Unsaved]=useState(false),[sound,Sound]=useState(true),[dark,Dark]=useState(()=>document.documentElement.dataset.theme==='dark'),[palette,Palette]=useState(()=>document.documentElement.dataset.palette||'forest'),[error,E]=useState(''),[view,V]=useState('home'),[flip,F]=useState(false),[feedback,FB]=useState(''),[queue,Q]=useState<number[]>([]),[sessionCount,SC]=useState(0),[revealing,Revealing]=useState(false),[now,Now]=useState(Date.now());const reviewTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const grading=useRef(false);useEffect(()=>()=>{if(reviewTimer.current)clearTimeout(reviewTimer.current)},[]);const lastAction=useRef(0);
 const audio=usePronunciation(sound);
 useEffect(()=>{if(ready&&view==='lesson'){const text=step<10||step>=13?activeWord.ar:arabic(current.examples[step-10].ids);audio.speak(text)}},[ready,view,p.lesson,p.step]);
 useEffect(()=>{const refresh=()=>Now(Date.now());const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[]);
 function load(){try{const loaded=readProgress(localStorage);P(loaded);if(!loaded.alphabet&&!loaded.completed.length&&loaded.step===0)V('welcome');else if(loaded.alphabet?.status==='learning'&&!loaded.completed.length&&loaded.step===0)V('alphabet');E('');}catch(e){E((e as Error).message||'Браузер не разрешает сохранение.');}Ready(true);}
 useEffect(()=>{load();try{Sound(localStorage.getItem('arabikos-sound')!=='off')}catch{};const otherTab=(e:StorageEvent)=>{if(e.key===KEY){load();V('home');F(false);Q([]);}};window.addEventListener('storage',otherTab);return()=>window.removeEventListener('storage',otherTab);},[]);
 function setSound(next:boolean){Sound(next);try{localStorage.setItem('arabikos-sound',next?'on':'off')}catch{}}
 function setTheme(next:boolean){Dark(next);document.documentElement.dataset.theme=next?'dark':'light';document.querySelector('meta[name="theme-color"]')?.setAttribute('content',next?'#18201c':'#344e40');try{localStorage.setItem('arabikos-theme',next?'dark':'light')}catch{}}
 function save(n:Progress){try{writeProgress(localStorage,n);Unsaved(false);E('');}catch{Unsaved(true);E('Браузер не сохранил прогресс. Разрешите хранение данных; не закрывайте страницу до сохранения.');}P(n);return true;}
 function acceptAction(){const now=performance.now();if(now-lastAction.current<160)return false;lastAction.current=now;return true;}
 const learned=dictionaryWords(p,now);const due=learned.filter(w=>(p.reviews[w.id]?.due??0)<=now);const weak=weakWords(p);const current=lessons[Math.min(p.lesson,lessons.length-1)];const step=p.step;const activeWord=current.words[step<10?step:Math.min(step-13,9)];
 function activity(n:Progress){const k=dayKey();return {...n,days:{...n.days,[k]:(n.days[k]??0)+1}};}
 function advance(){if(!acceptAction())return;if(step>=13&&sound)playAnswerSound(true);if(step===22){const completed=Array.from(new Set([...p.completed,current.id]));const reviews={...p.reviews};current.words.forEach(w=>{if(!reviews[w.id])reviews[w.id]={level:0,due:Date.now(),seen:0}});if(save(activity({...p,completed,reviews,lesson:Math.min(current.id+1,lessons.length-1),step:0})))V('complete');}else if(save({...p,step:step+1})){F(false);FB('');}}
 function cancelReveal(){if(reviewTimer.current)clearTimeout(reviewTimer.current);grading.current=false;Revealing(false);}
 function go(v:string){cancelReveal();V(v);F(false);FB('');}
 function review(){cancelReveal();Q(due.map(w=>w.id));SC(0);F(false);V('review');}
 function grade(known:boolean){if(!queue.length||grading.current||!acceptAction())return;grading.current=true;Revealing(true);F(true);if(sound)playAnswerSound(known);const id=queue[0],old=p.reviews[id]??{level:0,due:0,seen:0};save(activity({...p,reviews:{...p.reviews,[id]:scheduleReview(old,known,Date.now())}}));SC(c=>c+1);reviewTimer.current=setTimeout(()=>{Q(q=>q.slice(1));F(false);Revealing(false);grading.current=false;},750);}

 let streak=0;{const d=new Date();if(!p.days[dayKey(d)])d.setDate(d.getDate()-1);while(p.days[dayKey(d)]){streak++;d.setDate(d.getDate()-1);}}
 const nextDue=learned.map(w=>p.reviews[w.id]?.due??0).filter(t=>t>now).sort((a,b)=>a-b)[0];
 const arabic=(ids:number[])=>ids.map(id=>words[id].ar).join(' ');
 return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();go('home')}}><img className="brand-logo" src="./favicon.svg" alt=""/><span>Арабикос<small>ЧИТАТЬ. ПОНИМАТЬ.</small></span></a><div className="side-label">ВАША КНИГА</div><nav>{([['home','Главная',House],['alphabet','Алфавит',BookOpen],['lessons','Уроки',BookOpen],['dictionary','Мой словарь',Library],['practice','Практика',Layers]] as const).filter(([key])=>(key!=='alphabet'||p.alphabet?.status!=='skipped')).map(([key,label,Icon])=><button key={String(key)} className={(view===key||(key==='practice'&&['sentences','verbs'].includes(view))||(key==='dictionary'&&['review','wordbuilder'].includes(view)))?'nav active':'nav'} onClick={()=>go(String(key))}><Icon size={20}/><span>{String(label)}</span>{key==='dictionary'&&due.length>0&&<b>{due.length}</b>}</button>)}</nav><div className="side-bottom"><Leaf size={24}/><p>Знание растёт<br/>с каждой страницей.</p><small>По 10 слов за один шаг</small></div><span className="edition">АРАБСКИЙ ДЛЯ ПОНИМАНИЯ КОРАНА</span></aside>
 <div className="workspace"><header><span>Личная книга знаний{ready&&<small className="sync-status" role="status">{unsaved?'Не сохранено':'Сохранено в браузере'}</small>}</span><div><button className="sound-toggle" aria-label={sound?'Отключить звук':'Включить звук'} aria-pressed={sound} title={sound?'Отключить звук':'Включить звук'} onClick={()=>setSound(!sound)}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button className="sound-toggle" aria-label={dark?'Включить дневной режим':'Включить ночной режим'} aria-pressed={dark} title={dark?'Дневной режим':'Ночной режим'} onClick={()=>setTheme(!dark)}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button><button className="sound-toggle" aria-label="Настройки" title="Настройки" onClick={()=>go('settings')}><Settings size={20}/></button><Flame className="header-flame" size={17}/><span className="header-streak">{streak} {streak===1?'день':'дн.'} подряд</span><span className="avatar"><BookOpen size={16}/></span></div></header><main>
 {audio.message&&<p role="status">{audio.message}</p>}
 {error&&<div className="error" role="alert">{error} {!ready?<button onClick={load}>Повторить</button>:<button onClick={()=>save(p)}>Повторить сохранение</button>}</div>}
 {!ready?<div className="empty"><BookOpen/><h2>Открываем вашу книгу…</h2></div>:<>
 {view==='welcome'&&<AlphabetWelcome start={()=>{save({...p,alphabet:{status:'learning',passed:[]}});go('alphabet')}} skip={()=>{save({...p,alphabet:{status:'skipped',passed:[]}});go('home')}}/>}
 {view==='alphabet'&&<Alphabet progress={p.alphabet} sound={sound} onChange={alphabet=>save({...p,alphabet})} back={()=>go('home')}/>}
 {view==='home'&&<><div className="pageheading"><div><h1>Мой прогресс</h1></div></div><section className="stats"><div><span>Слов в вашей книге</span><strong>{learned.length}<small> / {words.length}</small></strong><ProgressBar className="line" value={learned.length/words.length*100} aria-label="Изучено слов"/></div><div><span>Уроков пройдено</span><strong>{p.completed.length}<small> / {lessons.length}</small></strong></div><div><span>Ждут повторения</span><strong>{due.length}<small> слов</small></strong><button className="textbtn" onClick={()=>go('dictionary')}>Открыть словарь</button></div></section>
 <Motivation/><div className="home-tracker"><section className="activity"><div className="section-title"><h3>Ритм занятий</h3><Flame size={19}/></div><strong>{streak}<small> дней подряд</small></strong><div className="week">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return <div key={i}><span>{d.toLocaleDateString('ru',{weekday:'short'})}</span><b className={p.days[dayKey(d)]?'filled':i===6?'today':''}>{p.days[dayKey(d)]?<Check size={16}/>:d.getDate()}</b></div>})}</div><p>{p.days[dayKey()]?'Сегодня вы уже сделали шаг вперёд.':'Один небольшой урок — хорошее начало дня.'}</p></section></div>
</>}
 {view==='lessons'&&<LessonsPage progress={p} openLesson={()=>go('lesson')}/>}
 {view==='lesson'&&<><button className="textbtn" onClick={()=>go('home')}><ChevronLeft size={17}/> К моей книге</button><div className="study-heading"><div><div className="eyebrow">УРОК {current.id+1} · {step<10?'СЛОВА':step<13?'ПРЕДЛОЖЕНИЯ':'ПРОВЕРКА'}</div><h1>{current.title}</h1></div><span>{step+1} / 23</span></div><ProgressBar className="line studyline" value={(step+1)/23*100} aria-label="Прогресс урока"/><section className="study-card" key={step}>{step<10?<><span className="eyebrow">СЛОВО {step+1} ИЗ 10</span><button className="arabic giant pronunciation" lang="ar" dir="rtl" aria-label={"Озвучить: "+activeWord.ar} onClick={()=>audio.speak(activeWord.ar)}>{activeWord.ar}</button><h2>{activeWord.ru}</h2><p>Прочитайте слово и запомните его смысл.</p><button className="primary" onClick={advance}>Дальше</button></>:step<13?<><span className="eyebrow">УЧЕБНОЕ ПРЕДЛОЖЕНИЕ {step-9} ИЗ 3</span><div className="arabic sentence" lang="ar" dir="rtl">{arabic(current.examples[step-10].ids)}</div><button className="textbtn center" onClick={()=>F(!flip)}>{flip?'Скрыть перевод':'Показать перевод'}</button>{flip&&<h2>{current.examples[step-10].ru}</h2>}<p>Все слова — из этого и предыдущих уроков.</p><button className="primary" onClick={advance}>Прочитал, дальше</button></>:<><span className="eyebrow">ВЫБЕРИТЕ ПЕРЕВОД · {step-12} / 10</span><button className="arabic giant pronunciation" lang="ar" dir="rtl" aria-label={"Озвучить: "+activeWord.ar} onClick={()=>audio.speak(activeWord.ar)}>{activeWord.ar}</button><div className="answers">{[activeWord,...current.words.filter(w=>w.id!==activeWord.id).slice(0,3)].sort((a,b)=>(a.id*7+step)%11-(b.id*7+step)%11).map(w=><button key={w.id} onClick={()=>{if(w.id===activeWord.id)advance();else {if(sound)playAnswerSound(false);FB('Попробуйте ещё раз.')}}} className={feedback==='Верно!'&&w.id===activeWord.id?'correct':''}>{w.ru}</button>)}</div><p role="status">{feedback||'Вспомните значение слова.'}</p></>}</section></>}
 {view==='complete'&&<section className="empty completion"><Check size={45}/><div className="eyebrow">ЕЩЁ ОДНА СТРАНИЦА</div><h1>Урок пройден!</h1><p>10 новых слов теперь в вашем словаре.<br/>Первое повторение уже доступно.</p><button className="primary" onClick={()=>go('dictionary')}>Закрепить слова в словаре</button><button className="textbtn center" onClick={()=>go('home')}>Вернуться на главную</button></section>}
 {view==='dictionary'&&<><div className="eyebrow">СОБРАНО ПО СЛОВУ</div><div className="section-title"><h1>Мой словарь <small>{learned.length}</small></h1></div>{!learned.length?<div className="empty"><Library size={40}/><h2>Здесь начнётся ваша коллекция</h2><p>Пройдите первый урок полностью — и в словаре появятся 10 слов.</p><button className="primary" onClick={()=>go('lesson')}>Открыть первый урок</button></div>:<><div className="dictionary-actions"><button className="dictionary-action" onClick={()=>go('wordbuilder')}>Трудные слова <b>{weak.length}</b></button><button className="primary dictionary-action" onClick={review}><Layers size={18}/>Карточки <b>{due.length}</b></button></div><div className="dictionary">{learned.map(w=><div key={w.id}><button className="arabic pronunciation" lang="ar" dir="rtl" aria-label={"Озвучить: "+w.ar} onClick={()=>audio.speak(w.ar)}>{w.ar}</button><div><strong>{w.ru}</strong><small>{repeatLabel(p.reviews[w.id]?.due??0,now)}</small></div></div>)}</div></>}</>}
 {view==='review'&&<><button className="textbtn" onClick={()=>go('dictionary')}><ChevronLeft size={17}/> Мой словарь</button><div className="eyebrow">ПОВТОРЕНИЕ С ИНТЕРВАЛАМИ</div><div className="section-title"><h1>Карточки словаря</h1><span>Осталось {queue.length}</span></div>{queue.length?<><button className={'flashcard '+(flip?'flipped':'')} onClick={()=>{if(!grading.current)F(!flip)}}>{flip?<strong className="flashcard-translation" lang="ru">{words[queue[0]].ru}</strong>:<><span className="eyebrow">ВСПОМНИТЕ ПЕРЕВОД</span><span className="arabic giant" lang="ar" dir="rtl">{words[queue[0]].ar}</span><span className="muted">Нажмите на карточку, чтобы посмотреть перевод</span></>}</button><div className="review-actions"><button disabled={revealing} onClick={()=>grade(false)}><RotateCcw size={18}/>Не помню</button><button disabled={revealing} className="primary" onClick={()=>grade(true)}><Check size={18}/>Помню</button></div><p className="swipe-note">После ответа перевод откроется на мгновение, затем появится следующее слово.</p><button className="textbtn center" onClick={()=>go('dictionary')}>Вернуться в словарь</button></>:<div className="empty"><Check size={40}/><h2>{sessionCount?'Отличная работа!':'На сейчас всё'}</h2><p>{learned.length?'Карточек к повторению пока нет. Они появятся, когда подойдёт время.':'Сначала завершите первый урок — здесь появятся ваши слова.'}</p>{learned.length?<>{nextDue&&<p>{repeatLabel(nextDue,now)}</p>}<button className="textbtn center" onClick={()=>go('dictionary')}>В словарь</button></>:<button className="primary" onClick={()=>go('lesson')}>Начать урок</button>}</div>}</>}
 {view==='wordbuilder'&&<WordBuilder ids={weak.map(w=>w.id)} sound={sound} onSuccess={(id,withoutHint)=>save(activity(clearDifficultWord(p,id,withoutHint)))} back={()=>go('dictionary')}/>}
 {view==='settings'&&<><section className="settings-panel alphabet-settings"><h2>Алфавит</h2><p>Буквы, огласовки и тест для начинающих.</p><button className="primary" onClick={()=>{save({...p,alphabet:{status:p.alphabet?.passed.length===28?'completed':'learning',passed:p.alphabet?.passed??[]}});go('alphabet')}}>Открыть алфавит</button></section><SettingsPage progress={p} sound={sound} dark={dark} palette={palette} setSound={setSound} setDark={setTheme} setPalette={next=>{Palette(next);document.documentElement.dataset.palette=next;try{localStorage.setItem('arabikos-palette',next)}catch{}}} onImport={data=>{writeProgress(localStorage,data);cancelReveal();P(data);Unsaved(false);E('');Q([]);}}/></>}
 {view==='practice'&&<PracticeHub completed={p.completed} open={go}/>}
 {view==='sentences'&&<><button className="textbtn practice-back" onClick={()=>go('practice')}>← Все тесты</button><SentencePractice key={p.completed.join(',')} completed={p.completed} sound={sound} onSuccess={()=>save(activity(p))}/></>}
 {view==='verbs'&&<><button className="textbtn practice-back" onClick={()=>go('practice')}>← Все тесты</button><VerbPractice completed={p.completed} sound={sound} onSuccess={()=>save(activity(p))}/></>}
 </>}
 <footer><span>АРАБИКОС</span><span>Прогресс хранится только в этом браузере. Очистка данных удалит его.</span><span>✦</span></footer></main></div></div>
}
