import {useState} from 'react';
import {BookOpen,Check,Lock,ChevronLeft} from 'lucide-react';
import {lessons,words,type Progress} from './lib/course';
export function LessonsPage({progress,openLesson}:{progress:Progress;openLesson:()=>void}){
 const [archive,A]=useState(false),[selected,S]=useState<number|null>(null);
 const pending=lessons.filter(l=>!progress.completed.includes(l.id)),done=lessons.filter(l=>progress.completed.includes(l.id));const lesson=done.find(l=>l.id===selected);
 if(archive&&lesson)return <><button className="textbtn practice-back" onClick={()=>S(null)}><ChevronLeft size={17}/>Пройденные уроки</button><div className="eyebrow">АРХИВ · УРОК {lesson.id+1}</div><h1>{lesson.title}</h1><p className="intro">{lesson.subtitle}</p><div className="dictionary archive-words">{lesson.words.map(w=><div key={w.id}><span className="arabic" lang="ar" dir="rtl">{w.ar}</span><strong>{w.ru}</strong></div>)}</div><h2 className="archive-examples-heading">Примеры из урока</h2><div className="archive-examples">{lesson.examples.map((e,i)=><section className="settings-panel" key={i}><div className="arabic" lang="ar" dir="rtl">{e.ids.map(id=>words[id].ar).join(' ')}</div><p>{e.ru}</p></section>)}</div></>;
 return <><div className="eyebrow">ОГЛАВЛЕНИЕ</div><h1>{archive?'Пройденные уроки':'Уроки'}</h1><div className="lesson-tabs"><button className={!archive?'selected':''} aria-pressed={!archive} onClick={()=>{A(false);S(null)}}>Уроки · {pending.length}</button><button className={archive?'selected':''} aria-pressed={archive} onClick={()=>{A(true);S(null)}}>Пройденные уроки · {done.length}</button></div><p className="intro">{archive?'Откройте урок, чтобы посмотреть его слова и примеры.':'Проходите уроки по порядку. Завершённые главы переходят в архив.'}</p>{!(archive?done:pending).length?<section className="empty"><Check size={35}/><h2>{archive?'Архив пока пуст':'Все уроки пройдены!'}</h2><p>{archive?'Первый завершённый урок появится здесь.':'Ваши слова и примеры доступны в пройденных уроках.'}</p>{!archive&&<button className="primary" onClick={()=>A(true)}>Пройденные уроки</button>}</section>:<div className="lesson-grid full">{(archive?done:pending).map(l=>{const locked=!archive&&l.id>progress.lesson;return <button key={l.id} className={'lesson-tile '+(locked?'locked':'')+(archive?' done':'')} disabled={locked} onClick={()=>archive?S(l.id):openLesson()}><div className="tile-top"><span>УРОК {String(l.id+1).padStart(2,'0')}</span>{archive?<Check size={18}/>:locked?<Lock size={16}/>:<BookOpen size={18}/>}</div><h3>{l.title}</h3><p>{l.subtitle}</p><div className="tile-bottom"><span>10 слов</span><span>{archive?'Посмотреть':locked?'Впереди':'Начать'}</span></div></button>})}</div>}<p className="source">Учебные предложения не выдаются за цитаты из Корана. <a href="https://corpus.quran.com/lemmas.jsp" target="_blank" rel="noreferrer">Справочник: Quranic Arabic Corpus</a>.</p></>;
}
