import {useState} from 'react';
import {Download,Upload,Moon,Sun,Volume2} from 'lucide-react';
import {type Progress} from './lib/course';
import {makeBackup,parseBackup} from './lib/backup';
import {playAnswerSound} from './lib/answer-sound';
type Props={progress:Progress;sound:boolean;dark:boolean;palette:string;setSound:(v:boolean)=>void;setDark:(v:boolean)=>void;setPalette:(v:string)=>void;onImport:(p:Progress)=>void};
export function SettingsPage({progress,sound,dark,palette,setSound,setDark,setPalette,onImport}:Props){
 const [candidate,C]=useState<Progress|null>(null),[message,M]=useState('');
 function download(){const url=URL.createObjectURL(new Blob([makeBackup(progress)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`arabikos-progress-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);M('Файл прогресса подготовлен для скачивания.');}
 async function read(file?:File){C(null);M('');if(!file)return;try{if(file.size>1024*1024)throw Error('Файл слишком большой. Выберите сохранённый файл Арабикоса.');C(parseBackup(await file.text()));}catch(e){M((e as Error).message);}}
 return <><div className="eyebrow">ВАША КНИГА — ВАШИ НАСТРОЙКИ</div><h1>Настройки</h1><div className="settings-grid"><section className="settings-panel"><h2>Оформление</h2><p className="muted">Режим и цвета сохраняются в этом браузере.</p><div className="setting-options"><button className={!dark?'chosen':''} aria-pressed={!dark} onClick={()=>setDark(false)}><Sun size={18}/>День</button><button className={dark?'chosen':''} aria-pressed={dark} onClick={()=>setDark(true)}><Moon size={18}/>Ночь</button></div><h3>Цвет книги</h3><div className="setting-options palettes">{[['forest','Лес'],['sand','Песок'],['ink','Чернила']].map(([key,label])=><button key={key} className={palette===key?'chosen':''} aria-pressed={palette===key} onClick={()=>setPalette(key)}><i className={'palette-dot '+key}/>{label}</button>)}</div></section><section className="settings-panel"><h2>Звуки</h2><label className="sound-setting"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/><Volume2 size={18}/>Звуки ответов</label><p className="muted">Мягкий перелив — верно, тихая низкая нота — попробуйте ещё раз.</p><div className="setting-options"><button disabled={!sound} onClick={()=>playAnswerSound(true)}>Послушать «верно»</button><button disabled={!sound} onClick={()=>playAnswerSound(false)}>Послушать «ошибка»</button></div></section><section className="settings-panel backup-panel"><h2>Сохранить и перенести прогресс</h2><p>Скачайте файл, чтобы сохранить копию или перенести занятия в другой браузер или на другое устройство. В файле — уроки, карточки и дни занятий.</p><div className="setting-options"><button onClick={download}><Download size={18}/>Скачать прогресс</button><label className="import-button"><Upload size={18}/>Импортировать файл<input type="file" accept=".json,application/json" onChange={e=>{void read(e.target.files?.[0]);e.target.value=''}}/></label></div>{candidate&&<div className="import-preview"><p>В файле: {candidate.completed.length} уроков, {candidate.completed.length*10} слов. Импорт заменит текущий прогресс. Сначала можно скачать его копию.</p><button className="primary" onClick={()=>{try{onImport(candidate);C(null);M('Прогресс восстановлен. Можно продолжать занятия.')}catch{M('Браузер не сохранил импорт. Текущий прогресс не изменён.')}}}>Восстановить прогресс</button><button className="textbtn" onClick={()=>C(null)}>Отмена</button></div>}<p role="status">{message}</p></section></div></>;
}
