const fs=require('fs'),vm=require('vm'),assert=require('assert'),ts=require(process.cwd()+'/node_modules/typescript');let timers=[];
function load(file,imports={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:m.exports,module:m,require:n=>n in imports?imports[n]:require(require.resolve(n,{paths:[process.cwd()]})),Date,structuredClone,window:{},setTimeout:fn=>{timers.push(fn);return 1},clearTimeout:()=>{}});return m.exports}
let active;const frames=new Map();const react={useState:init=>{const f=active,i=f.pos++;if(!(i in f.state))f.state[i]=typeof init==='function'?init():init;return[f.state[i],v=>f.state[i]=typeof v==='function'?v(f.state[i]):v]},useRef:init=>{const f=active,i=f.pos++;return f.state[i]??(f.state[i]={current:init})},useEffect:()=>{}};
function render(el,path='r'){if(!el||typeof el!=='object')return el;if(Array.isArray(el))return el.map((v,i)=>render(v,path+'/'+i));if(typeof el.type==='function'){const key=path+':'+(el.key??'')+':'+el.type.name;let f=frames.get(key);if(!f){f={state:[],pos:0};frames.set(key,f)}f.pos=0;active=f;return render(el.type(el.props),key)}return {...el,props:{...el.props,children:render(el.props.children,path+'/c')}}}
function all(el,pred,out=[]){if(Array.isArray(el))el.forEach(e=>all(e,pred,out));else if(el&&typeof el==='object'){if(pred(el))out.push(el);all(el.props?.children,pred,out)}return out}
const alphabet=load('pages-app/lib/alphabet.ts');const course=load('pages-app/lib/course.ts');const storage=load('pages-app/lib/storage.ts',{'./course':course,'./alphabet':alphabet});const backup=load('pages-app/lib/backup.ts',{'./storage':storage});const ui=load('pages-app/Alphabet.tsx',{'react':react,'./lib/alphabet':alphabet,'./lib/answer-sound':{playAnswerSound:()=>{}},'./lib/pronunciation':{usePronunciation:()=>({available:false,message:'',speak:()=>{}})}});
assert.equal(alphabet.letters.length,28);assert.equal(new Set(alphabet.letters.map(l=>l.ar)).size,28);for(const l of alphabet.letters){assert.equal(l.forms.length,4);assert(l.name&&l.speech&&l.sound);if('ادذرزو'.includes(l.ar)){assert.equal(l.forms[1],l.ar);assert.equal(l.forms[2],'ـ'+l.ar);assert.equal(l.forms[3],'ـ'+l.ar)}else{assert.equal(l.forms[1],l.ar+'ـ');assert.equal(l.forms[2],'ـ'+l.ar+'ـ')}}
for(let i=0;i<28;i++)for(let k=0;k<20;k++){const q=alphabet.alphabetQuestion(i);assert.equal(q.options.length,4);assert.equal(new Set(q.options.map(o=>o.id)).size,4);assert.equal(q.options.filter(o=>o.id===i).length,1);assert(q.options.every(o=>o.ar===alphabet.letters[o.id].forms[q.position]))}
assert(storage.validateProgress(course.initial));assert(!storage.validateProgress({...course.initial,alphabet:{status:'completed',passed:[0]}}));assert(!storage.validateProgress({...course.initial,alphabet:{status:'learning',passed:[0,0]}}));assert(!storage.validateProgress({...course.initial,alphabet:{status:'learning',passed:[28]}}));const a={...course.initial,alphabet:{status:'learning',passed:[1,2,3]}};assert.equal(JSON.stringify(backup.parseBackup(backup.makeBackup(a)).alphabet),JSON.stringify(a.alphabet));assert(storage.validateProgress(backup.parseBackup(backup.makeBackup(course.initial))));
let changes=0,progress={status:'learning',passed:[]};const root={type:ui.Alphabet,props:{progress,sound:false,onChange:p=>{root.props.progress=progress=p;changes++},back:()=>{}}};let tree=render(root);assert.equal(all(tree,e=>e.props?.className==='alphabet-letter').length,28);all(tree,e=>e.type==='button'&&e.props.children==='Тест')[0].props.onClick();for(let i=0;i<28;i++){tree=render(root);const title=all(tree,e=>e.type==='h2')[0].props.children;const letter=alphabet.letters.find(l=>l.name===title);const options=all(tree,e=>e.props?.className==='answers alphabet-answers')[0];const buttons=all(options,e=>e.type==='button');assert.equal(buttons.length,4);const right=buttons.find(b=>letter.forms.includes(b.props.children));const wrong=buttons.find(b=>b!==right);const before=changes;wrong.props.onClick();assert.equal(changes,before);assert.equal(timers.length,0);right.props.onClick();right.props.onClick();assert.equal(changes,before+1);assert.equal(timers.length,1);timers.shift()()}
assert.equal(progress.status,'completed');assert.equal(progress.passed.length,28);tree=render(root);assert(all(tree,e=>e.type==='h2'&&e.props.children==='Все буквы этого теста пройдены!').length);frames.clear();root.props.progress={status:'learning',passed:Array.from({length:27},(_,i)=>i)};tree=render(root);all(tree,e=>e.type==='button'&&e.props.children==='Тест')[0].props.onClick();tree=render(root);assert(all(tree,e=>e.type==='h2'&&e.props.children==='Йа').length);console.log('PASS: 28 letters, contextual forms, four distinct options, legacy/backup validation, wrong/duplicate answers, completion and resumable test');
