const fs=require('fs'),vm=require('vm'),assert=require('assert'),ts=require(process.cwd()+'/node_modules/typescript');let timers=[];
function load(file,imports={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports:m.exports,module:m,require:n=>n==='./sentence-bank'?load('pages-app/lib/sentence-bank.ts'):n in imports?imports[n]:require(require.resolve(n,{paths:[process.cwd()]})),Date,structuredClone,setTimeout:fn=>{timers.push(fn);return 1},clearTimeout:()=>{}});return m.exports}
let active;const frames=new Map();const react={useState:init=>{const f=active,i=f.pos++;if(!(i in f.state))f.state[i]=typeof init==='function'?init():init;return[f.state[i],v=>f.state[i]=typeof v==='function'?v(f.state[i]):v]},useRef:init=>{const f=active,i=f.pos++;return f.state[i]??(f.state[i]={current:init})},useEffect:()=>{}};
function render(el,path='r'){if(!el||typeof el!=='object')return el;if(Array.isArray(el))return el.map((v,i)=>render(v,path+'/'+i));if(typeof el.type==='function'){const key=path+':'+(el.key??'')+':'+el.type.name;let f=frames.get(key);if(!f){f={state:[],pos:0};frames.set(key,f)}f.pos=0;active=f;return render(el.type(el.props),key)}return {...el,props:{...el.props,children:render(el.props.children,path+'/c')}}}
function all(el,pred,out=[]){if(Array.isArray(el))el.forEach(e=>all(e,pred,out));else if(el&&typeof el==='object'){if(pred(el))out.push(el);all(el.props?.children,pred,out)}return out}
const course=load('pages-app/lib/course.ts');const forms=load('pages-app/lib/verb-forms.ts',{'./course':course});const spelling=load('pages-app/lib/spelling.ts',{'./course':course});const examples=load('pages-app/lib/practice-examples.ts',{'./course':course});const practice=load('pages-app/Practice.tsx',{'./lib/practice-examples':examples,'react':react,'./lib/course':course,'./lib/verb-forms':forms,'./lib/answer-sound':{playAnswerSound:()=>{}}});
assert.equal(forms.practicedVerbs([0,1,2,3,4,5,6]).length,0);assert.equal(forms.practicedVerbs([0,1,2,3,4,5,6,7]).length,10);assert.equal(forms.practicedVerbs(Array.from({length:20},(_,i)=>i)).length,30);for(const v of course.words.filter(w=>w.kind==='verb')){const items=forms.formsFor(v.id);assert.equal(items.length,9);assert.equal(new Set(items.map(f=>f.ar)).size,9);assert(items.every(f=>f.ru&&!f.ru.includes('undefined')&&f.ar));}assert.equal(forms.formsFor(151)[2].ru,'Она обратилась с мольбой');assert.equal(forms.formsFor(152)[8].ru,'Он простит');assert.equal(forms.formsFor(158)[3].ar,'آخُذُ');
const onlyMissed={completed:[0],lesson:1,step:0,reviews:{0:{level:1,due:0,seen:1,lastKnown:true,misses:0},1:{level:4,due:0,seen:8,lastKnown:true,misses:2},2:{level:5,due:0,seen:9,lastKnown:false}},days:{}};assert.equal(spelling.weakWords(onlyMissed).map(w=>w.id).sort().join(','),'1,2');
frames.clear();timers=[];let formSuccess=0;const verbRoot={type:practice.VerbPractice,props:{completed:[0,1,2,3,4,5,6,7],sound:false,onSuccess:()=>formSuccess++}};let tree=render(verbRoot);assert.equal(all(tree,e=>e.props?.className==='verb-choice').length,10);all(tree,e=>e.props?.className==='verb-choice')[0].props.onClick();tree=render(verbRoot);for(const form of forms.formsFor(70)){tree=render(verbRoot);assert.equal(all(tree,e=>e.props?.className==='practice-prompt')[0].props.children,form.ru);const options=all(tree,e=>e.props?.className==='answers verb-answers')[0];const buttons=all(options,e=>e.type==='button');assert.equal(buttons.length,4);const wrong=buttons.find(b=>b.props.children!==form.ar);wrong.props.onClick();assert.equal(timers.length,0);tree=render(verbRoot);const right=all(tree,e=>e.type==='button'&&e.props.children===form.ar)[0];right.props.onClick();assert.equal(timers.length,1);timers.shift()();}tree=render(verbRoot);assert.equal(formSuccess,9);assert(all(tree,e=>e.type==='h2'&&e.props.children==='Глагол повторён!').length);all(tree,e=>e.type==='button'&&e.props.children==='Выбрать другой глагол')[0].props.onClick();tree=render(verbRoot);const choices=all(tree,e=>e.props?.className==='verb-choice');assert.equal(choices.length,10);choices[4].props.onClick();tree=render(verbRoot);assert.equal(all(tree,e=>e.props?.className==='practice-prompt')[0].props.children,forms.formsFor(74)[0].ru);all(tree,e=>e.props?.className==='textbtn verb-back')[0].props.onClick();tree=render(verbRoot);assert.equal(all(tree,e=>e.props?.className==='verb-choice').length,10);frames.clear();verbRoot.props.completed=Array.from({length:20},(_,i)=>i);tree=render(verbRoot);assert.equal(all(tree,e=>e.props?.className==='verb-choice').length,30);frames.clear();verbRoot.props.completed=[0,1,2,3,4,5,6];tree=render(verbRoot);assert.equal(all(tree,e=>e.props?.className==='verb-choice').length,0);console.log('PASS: only explicitly forgotten words, learned-verb gates, 315 distinct forms, study then nine person/tense questions, wrong answers do not advance');
